schema:
  format:
    openapi: "3.0.0"
  service_input_type: "LoadBalancedFargateServiceInput"
  pipeline_input_type: "PipelineInputs"

  types:
    LoadBalancedFargateServiceInput:
      type: object
      description: "Input properties for a loadbalanced Fargate service"
      properties:
        port:
          title: "Port"
          type: number
          description: "The port to route traffic to"
          default: 80
          minimum: 0
          maximum: 65535
        desired_count:
          title: "Desired count"
          type: number
          description: "The default number of Fargate tasks you want running"
          default: 1
          minimum: 1
        task_size:
          title: "Task size"
          type: string
          description: "The size of the task you want to run"
          enum: ["x-small", "small", "medium", "large", "x-large"]
          default: "x-small"
        image:
          title: "Image"
          type: string
          description: "The name/url of the container image"
          default: "public.ecr.aws/nginx/nginx:1.21"
          minLength: 1
          maxLength: 200
        otel_image:
          title: "AWS Distro for OpenTelemetry Collector image URI"
          type: string
          description: "The name/url of the OTEL container image"
          default: "public.ecr.aws/aws-observability/aws-otel-collector:latest"
          minLength: 1
          maxLength: 200
        otel_loglevel:
          title: "OpenTelemetry Collector log level"
          type: string
          description: "ADOT OTEL collector log level for Prometheus etc. Output can be seen in ECS Task Logs and CloudWatch Logs."
          enum: ["debug", "info", "warn", "error"]
          default: "info"
        backendurl:
          title: "Backend URL"
          type: string
          description: "Service discovery url of the backend service"
          default: "backend-svc-inst.backend-svc.fargate-env.local:80"
          minLength: 1
          maxLength: 200
        fq_parent_domain:
          title: "Fully Qualified Parent Domain eg. demo01.staging.containerofferings.com"
          type: string
          description: "Full FQDN will be <service.name>.<fq_parent_domain>. eg. sample-app-01.demo01.staging.containerofferings.com"
          minLength: 1
          maxLength: 200
        listener_rule_priority:
          title: "Application Load Balancer Listener Rule priority"
          type: number
          description: "Listener rule priority, must not collide with existing services."
          default: 1000
          minimum: 10
          maximum: 49999

    PipelineInputs:
      type: object
      description: "Pipeline input properties"
      properties:
        service_dir:
          title: "Application Code Directory"
          type: string
          description: "Source directory for the service"
          default: "app"
          minLength: 1
          maxLength: 100
        dockerfile:
          title: "Dockerfile"
          type: string
          description: "The location of the Dockerfile to build"
          default: "Dockerfile"
          minLength: 1
          maxLength: 100
        unit_test_command:
          title: "Unit test command"
          type: string
          description: "The command to run to unit test the application code"
          default: "echo 'add your unit test command here'"
          minLength: 1
          maxLength: 200
