AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a service on AWS Fargate, hosted in a public or private subnet, and accessible via a public load balancer.
Mappings:
  TaskSize:
    x-small:
      cpu: 256
      memory: 512
    small:
      cpu: 512
      memory: 1024
    medium:
      cpu: 1024
      memory: 2048
    large:
      cpu: 2048
      memory: 4096
    x-large:
      cpu: 4096
      memory: 8192

Resources:
  LoadBalancerSecurityGrouptoServiceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroupEgress'
    Properties:
      GroupId: '{{ environment.outputs.LoadBalancerSecurityGroupId }}'
      IpProtocol: tcp
      Description: Load balancer to target
      DestinationSecurityGroupId: !GetAtt
        - ServiceSecurityGroup
        - GroupId
      FromPort: '{{ service_instance.inputs.port }}'
      ToPort: '{{ service_instance.inputs.port }}'
  
  ServiceTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Port: '{{ service_instance.inputs.port }}'
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: stickiness.enabled
          Value: 'false'
        - Key: deregistration_delay.timeout_seconds
          Value: '60'
      TargetType: ip
      VpcId: '{{ environment.outputs.VPC }}'
      HealthCheckIntervalSeconds: 6
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3

  ServiceListenerRule1:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ServiceTargetGroup
      Conditions:
        - Field: host-header
          Values:
              - !Join [ '', [ '{{ service.name }}', ., '{{ service_instance.inputs.fq_parent_domain }}'] ]
      ListenerArn: '{{ environment.outputs.LoadBalancerHttpsListenerArn }}'
      Priority: {{ service_instance.inputs.listener_rule_priority }}

  ServiceTaskDefTaskRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
        Version: 2012-10-17
      Policies:
        - PolicyName: 'Publish2SNS'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 'sns:Publish'
                Resource: '{{ environment.outputs.SNSTopicArn }}'
      ManagedPolicyArns:
        - !Ref BaseTaskRoleManagedPolicy
        - !Ref AwsOtelManagedPolicy
        {{ service_instance.components.default.outputs
            | proton_cfn_iam_policy_arns }}

  # Basic permissions for writing metrics and log events to Cloudwatch and X-Ray, this is something that would typically
  # be required by every production-ready service.
  BaseTaskRoleManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "cloudwatch:PutMetricData"
              - "logs:PutLogEvents"
            Resource: "*"
          - Effect: Allow
            Action:
              - 's3:ListAllMyBuckets'
            Resource: "*"

  AwsOtelManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'xray:GetSamplingStatisticSummaries'
              - 'xray:GetSamplingRules'
              - 'xray:GetSamplingTargets'
              - 'xray:PutTelemetryRecords'
              - 'xray:PutTraceSegments'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'logs:PutLogEvents'
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:DescribeLogStreams'
              - 'logs:DescribeLogGroups'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'ssm:GetParameters'
              - 'ssm:GetParameter'  
            Resource: 'arn:aws:ssm:*:*:parameter/{{ environment.outputs.OtelCollectorConfigSsmParameterName }}'
          - Sid: 'PrometheusRemoteWrite'
            Effect: Allow
            Action:
              - 'aps:RemoteWrite'
            Resource: '*'

  ServiceTaskDef:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ContainerDefinitions:
        - Essential: true
          Image: '{{ service_instance.inputs.image }}'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ServiceTaskDefLogGroup
              awslogs-stream-prefix: '{{ service.name }}/{{ service_instance.name }}'
              awslogs-region: !Ref 'AWS::Region'
          Name: '{{ service_instance.name }}'
          PortMappings:
            - ContainerPort: '{{ service_instance.inputs.port }}'
              Protocol: tcp
          Environment:
            - Name: SNS_TOPIC_ARN
              Value: '{"ping":"{{ environment.outputs.SNSTopicArn }}"}'
            - Name: SNS_REGION
              Value: "{{ environment.outputs.SNSRegion }}"
            - Name: BACKEND_URL
              Value: "{{ service_instance.inputs.backendurl }}"
            {% if service_instance.components.default.outputs | length > 0 %}
            {{ service_instance.components.default.outputs |
                proton_cfn_ecs_task_definition_formatted_env_vars }}
            {% endif %}
          HealthCheck:
            Command: ["CMD-SHELL", "curl -f http://localhost/ || exit 1" ]
            Interval: 10
            Retries: 4
            StartPeriod: 60
            Timeout: 5
        - Essential: true
          Image: '{{ service_instance.inputs.otel_image }}'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ServiceTaskDefLogGroup
              awslogs-stream-prefix: '{{ service.name }}/{{ service_instance.name }}-otel-sidecar-collector'
              awslogs-region: !Ref 'AWS::Region'
          Name: '{{ service_instance.name }}-otel-collector'
          Command: ["--config=/etc/ecs/container-insights/otel-task-metrics-config.yaml"]
          Secrets:
            - Name: AOT_CONFIG_CONTENT
              ValueFrom: '{{ environment.outputs.OtelCollectorConfigSsmParameterName }}'
          Environment:
           - Name: OTEL_METRICS_EXPORTER
             Value: prometheus
           - Name: OTEL_LOG_LEVEL
             Value: '{{ service_instance.inputs.otel_loglevel }}'
           - Name: OTEL_SERVICE_NAME
             Value: '{{ service.name }}_{{ service_instance.name }}'
           - Name: AWS_PROMETHEUS_ENDPOINT
             Value: '{{ environment.outputs.PrometheusWorkSpaceRemoteWriteEndpoint }}'
            {% if service_instance.components.default.outputs | length > 0 %}
            {{ service_instance.components.default.outputs |
                proton_cfn_ecs_task_definition_formatted_env_vars }}
            {% endif %}
      Cpu: !FindInMap [TaskSize, {{ service_instance.inputs.task_size }}, cpu]
      ExecutionRoleArn: '{{ environment.outputs.ServiceTaskDefExecutionRoleArn }}'
      Family: '{{ service.name }}_{{ service_instance.name }}'
      Memory: !FindInMap [TaskSize, {{ service_instance.inputs.task_size }}, memory]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn: !GetAtt
        - ServiceTaskDefTaskRole
        - Arn
  ServiceTaskDefLogGroup:
    Type: 'AWS::Logs::LogGroup'
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  Service:
    Type: 'AWS::ECS::Service'
    Properties:
      ServiceName: '{{ service.name }}_{{ service_instance.name }}'
      Cluster: '{{ environment.outputs.Cluster }}'
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      DesiredCount: '{{ service_instance.inputs.desired_count }}'
      EnableECSManagedTags: false
      HealthCheckGracePeriodSeconds: 60
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: '{{ service_instance.name }}'
          ContainerPort: '{{ service_instance.inputs.port }}'
          TargetGroupArn: !Ref ServiceTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !GetAtt
              - ServiceSecurityGroup
              - GroupId
          Subnets:
            - '{{ environment.outputs.PrivateSubnet1 }}'
            - '{{ environment.outputs.PrivateSubnet2 }}'
            - '{{ environment.outputs.PrivateSubnet3 }}'
      ServiceRegistries:
        - RegistryArn: !GetAtt
            - CloudMapService
            - Arn
      TaskDefinition: !Ref ServiceTaskDef
    DependsOn:
      - ServiceTargetGroup
  CloudMapService:
    Type: 'AWS::ServiceDiscovery::Service'
    Properties:
      DnsConfig:
        DnsRecords:
          - TTL: 60
            Type: A
        NamespaceId: '{{ environment.outputs.CloudMapNamespaceId }}'
        RoutingPolicy: MULTIVALUE
      HealthCheckCustomConfig:
        FailureThreshold: 1
      Name: '{{ service_instance.name }}.{{ service.name }}'
      NamespaceId: '{{ environment.outputs.CloudMapNamespaceId }}'
  ServiceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Automatically created Security Group for the Service
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: '-1'
      VpcId: '{{ environment.outputs.VPC }}'
  ServiceSecurityGroupfromLoadBalancerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      IpProtocol: tcp
      Description: Load balancer to targets
      GroupId: !GetAtt
        - ServiceSecurityGroup
        - GroupId
      FromPort: '{{ service_instance.inputs.port }}'
      ToPort: '{{ service_instance.inputs.port }}'
      SourceSecurityGroupId: '{{ environment.outputs.LoadBalancerSecurityGroupId }}'
  TaskCountTarget:
    Type: 'AWS::ApplicationAutoScaling::ScalableTarget'
    DependsOn: Service
    Properties:
      MaxCapacity: 10
      MinCapacity: 1
      ResourceId: !Join
        - ''
        - - service/
          - '{{ environment.outputs.Cluster }}'
          - /
          - '{{ service.name }}_{{ service_instance.name }}'
      RoleARN: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService
      ScalableDimension: 'ecs:service:DesiredCount'
      ServiceNamespace: ecs
  TaskCountTargetCpuScaling:
    Type: 'AWS::ApplicationAutoScaling::ScalingPolicy'
    Properties:
      PolicyName: LBFargateServiceTaskCountTargetCpuScaling
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref TaskCountTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        TargetValue: 50
  TaskCountTargetMemoryScaling:
    Type: 'AWS::ApplicationAutoScaling::ScalingPolicy'
    Properties:
      PolicyName: LBFargateServiceTaskCountTargetMemoryScaling
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref TaskCountTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageMemoryUtilization
        TargetValue: 50
  RouteHealthCheck: 
    Type: 'AWS::Route53::HealthCheck'
    Properties: 
      HealthCheckConfig: 
      Port: 443
      Type: HTTPS
      ResourcePath: '{{ service.inputs.ResourcePath }}'
      FullyQualifiedDomainName: '{{ service.inputs.FullyQualifiedDomainName }}'
      RequestInterval: '{{ service_instance.inputs.RequestInterval }}'
      FailureThreshold: '{{ service_instance.inputs.FailureThreshold }}'
      
  RouteHealthCheckAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties: 
      ActionsEnabled: Boolean
      AlarmActions: 
        - '{{ environment.outputs.SNSTopicArnEmail }}'
      AlarmDescription: 'Health check alarm'
      AlarmName: 'HealthCheckAlarm'
      ComparisonOperator: 'LessThanThreshold'
      DatapointsToAlarm: Integer
      Dimensions: 
        - Name: Route53healthcheck
          Value: !Ref RouteHealthCheck
      MetricName: Healthcheckstatus
      Namespace: 'AWS/Route53'
      Period: 30
      Statistic: 'Minimum'
      Threshold: '1.0'
Outputs:
  ServiceURL:
    Value: 'https://{{ service.name }}.{{ service_instance.inputs.fq_parent_domain }}/'